#!/bin/bash
###User's Input File and Output File
INPUTNAME=$JOBNAME.xyz
INPUTDIR=$DIR_NAME
echo $HOSTNAME
echo $INPUTDIR
###Copy file to local filesystem /tmp
JOB_RUN_DIR=/tmp/$USER/$JOB_ID
mkdir -p $JOB_RUN_DIR

/bin/cp $INPUTDIR/$INPUTNAME $JOB_RUN_DIR/

cd $JOB_RUN_DIR

## xTB environment
export PATH=$PATH:/software/xtb/bin
export XTBPATH=/software/xtb/share/xtb
export OMP_NUM_THREADS=4
export MKL_NUM_THREADS=4
export OMP_STACKSIZE=1000m
ulimit -s unlimited

if [ -z $CHARGE ]; then
  CHARGE=0
fi

## no constraint
## run xTB pre-optimization
xtb $INPUTNAME --opt --gfn2 --chrg $CHARGE
## run CREST program
crest2 xtbopt.xyz --T 4 --chrg $CHARGE

## Delete tmp files and copy file from local /tmp to NFS filesystem /home
rm -f coord*
rm -f cregen*
rm -f cre_members
rm -f gfnff*
rm -f struc.xyz
rm -f wbo
cp -rf $JOB_RUN_DIR $INPUTDIR/
rm -rf $JOB_RUN_DIR/

